name: Build check

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'            # We don't want this to run on release
  pull_request:

jobs:
  build-ubuntu20:
    name: Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master

      - name: Build
        id: build
        run: |
          sudo apt install -y libboost-all-dev
          build_folder="bin"
          plura_ver=${GITHUB_SHA::7}
          release_name=plura-cli-ubuntu20.04-"$plura_ver"
          mkdir -p "$build_folder"
          cd "$build_folder"
          cmake -j2 -D ARCH=default -D CMAKE_BUILD_TYPE=Release -D CMAKE_POSITION_INDEPENDENT_CODE:BOOL=true -D BOOST_IGNORE_SYSTEM_PATHS_DEFAULT=ON -D BOOST_ROOT=/usr ..
          make
          mkdir -p "$release_name"
          exeFiles=()
          #for f in src/*; do [[ -x $f && -f $f ]] && exeFiles+=( "$f" ); done
          #strip "${exeFiles[@]}"
          cp "${exeFiles[@]}" "$release_name/"
          echo "::set-output name=release_name::${release_name}"
          echo "::set-output name=artifact_path::$build_folder/$release_name"

      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ steps.build.outputs.release_name }}
          path: ${{ steps.build.outputs.artifact_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  

  
